version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/core"
    schedule:
      interval: "daily"

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
